CREATE TABLE CUSTOMERSS(CUSTMID INT PRIMARY KEY,CUSTMNAME VARCHAR(40))
INSERT CUSTOMERSS VALUES(1,'ALICE')
INSERT CUSTOMERSS VALUES(2,'BOB')
INSERT CUSTOMERSS VALUES(3,'CHARLIE')
CREATE TABLE ORDERS(ORDERPH INT,PRODUCT VARCHAR(40),ORDERID INT FOREIGN KEY REFERENCES CUSTOMERSS)
INSERT ORDERS VALUES(101,'PILLOW',1)
INSERT ORDERS VALUES(102,'BOOKS',2)
SELECT * FROM CUSTOMERSS CROSS JOIN ORDERS
SELECT * FROM CUSTOMERS
SELECT * FROM ORDERS
DROP TABLE CUSTOMERSS
DROP TABLE ORDERS